login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.logIn, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logOut, name='logOut'),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.forms, name='forms'),
    path('confirmation/', views.konfirmasi, name='confirmation'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('story8', include('story8.urls')),
    path('book/', include('story9.urls')),
    path('login/', include('login.urls')),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('like/', views.like, name='like'),
]

login/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Person(models.Model):
    nama = models.CharField('Nama', max_length=30)
    pesan = models.TextField('Pesan')

    def __str__(self):
        return self.nama

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    book_id = models.CharField(max_length=300, primary_key=True, unique=True)
    title = models.CharField(max_length=300)
    publisher = models.CharField(max_length=300)
    thumbnail = models.CharField(max_length=300)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ('-likes',)

    def __str__(self):
        return self.title

    objects = models.Manager()

login/forms.py
from django import forms


class Login_Form(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'title': 'Username',
        'required': True,
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'required': True,
    }))

status/forms.py
from django import forms
from .models import Person
from django.forms import ModelForm

class Messages_Form(ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import *

def logIn(request):
    form = Login_Form()
    if(request.method == "POST"):
        form = Login_Form(request.POST)
        if(form.is_valid()):
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if(user is not None):
                login(request, user)
                return redirect('/login/')
            else:
                messages = ['Incorrect username or password!']
                response = {'form': form, 'messages': messages}
                return render(request, 'login.html', response)
    else:
        response = {'form': form}
        return render(request, 'login.html', response)


def logOut(request):
    logout(request)
    return redirect('/login/')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/login/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

status/views.py
from django.shortcuts import render
from .models import Person
from .forms import Messages_Form

# Create your views here.
def forms(request):
    if request.method == 'POST':
        form = Messages_Form(request.POST)
        if form.is_valid():
            nama = request.POST['nama']
            pesan = request.POST['pesan']
            Person.objects.create(nama = nama,pesan = pesan)

    persons = Person.objects.all()
    form = Messages_Form()

    return render(request, 'forms.html', {'persons':persons, 'form':form})

def konfirmasi(request):
    if request.method == 'POST':
        form = Messages_Form(request.POST)
        return render(request, 'konfirmasi.html', {'nama':form.data['nama'], 'pesan':form.data['pesan']})

story8/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index.html")

story9/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import *
import json

@csrf_exempt
def index(request):
    if(request.method == "POST"):
        books = list(Book.objects.values()[:5])
        return HttpResponse(json.dumps(books))
    else:
        return render(request, 'book.html')

@csrf_exempt
def like(request):
    if (request.method == "POST"):
        book_id = request.POST['book_id']
        title = request.POST['title']
        publisher = request.POST['publisher']
        thumbnail = request.POST['thumbnail']
        book, created = Book.objects.get_or_create(book_id=book_id, title=title, publisher=publisher, thumbnail=thumbnail)
        book.likes += 1
        book.save()
        return HttpResponse(book.likes)

login/templates/includes/_navbar.html
{% load static %}
<!DOCTYPE html>
<nav class="navbar navbar-expand-sm navbar-dark">
    <a class="navbar-brand" href="#">Judul</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSmall">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSmall">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="#" class="nav-link">Story 7</a
          ></li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 8</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 9</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 10</a>
      </li>
    </ul>
  </div>
  </nav>

login/templates/includes/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>Rafli</title>
    
  </head>
  <body>
    <!-- Navbar -->
  {% include 'includes/_navbar.html' %}
  {% block body %}
  {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

login/templates/login.html
{% extends 'includes/base.html' %}
{% load static %}
{% block body %}
<div class="text-center" style="margin-left: 100px; margin-right: 100px;">
    <h1>Login</h1>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-secondary" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
        {% if user.is_authenticated %}
    <h2 id="username-display">Welcome, {{user.username}}</h2>
    <div class="centre-items tombol">
        <a class="btn custom-button" href="{% url 'login:logOut' %}" id='logout'>Logout</a>
    </div>

    {% else %}
    <div class='form'>
        <form action="" method="POST">
            {% csrf_token %} {{ form }}
            <div class="centre-items" style="margin-top: 2vh; margin-bottom: 2vh;">
                <input type="submit" class="btn custom-button" value="Login" id="submit">
            </div>
        </form>
        <a href="{% url 'login:signup' %}" style="color: rgb(148, 148, 148);"
        id="sign-up">Sign up here</a>!
        {% endif %}
</div>

{% endblock %}

login/templates/signup.html
{% extends 'includes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<div class="text-center">
    <h1>Sign Up</h1>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-secondary" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field|as_crispy_field }}
        </div>
        {% endfor %}
        <button type="submit" id="submit-button">Sign up</button>
    </form>
</div>
{% endblock %}

status/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>Rafli Bangsawan</title>
  </head>
  <body>
    <!-- Navbar -->
  {% include 'includes/_navbar.html' %}
  {% block body %}
  {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

status/templates/forms.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <form action="confirmation/" method="POST">
        <table>
            {% csrf_token %}
            {{ form }}
        </table>
        <input type="submit" value="Submit" name="submit-btn">
    </form>
</div>

<div>
    <table>
        {% for person in persons %}
            <tr>
                <td>Name: {{ person.nama }}</td>
                <td>Message: {{ person.pesan }}</td>
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

status/templates/includes/_navbar.html
{% load static %}
<!DOCTYPE html>
<nav class="navbar navbar-expand-sm navbar-dark">
    <a class="navbar-brand" href="#">Judul</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSmall">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSmall">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="#" class="nav-link">Story 7</a
          ></li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 8</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 9</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 10</a>
      </li>
    </ul>
  </div>
  </nav>

status/templates/konfirmasi.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <h1>Apa kamu yakin akan mengirim pesan ini?</h1>
    <p>Nama: {{ nama }}</p>
    <p>Pesan: {{ pesan }}</p>
    <div>
        <form action="/" method="POST">
            {% csrf_token %}
            <input type="hidden" name="nama" value="{{ nama }}">
            <input type="hidden" name="pesan" value="{{ pesan }}">

            <input type="submit" value="Confirm" name="confirm">
        </form>

        <form action="/" method="GET">
            <input type="submit" value="Cancel" name="cancel">
        </form>
    </div>

{% endblock %}

story8/templates/includes/_navbar.html
{% load static %}
<!DOCTYPE html>
<nav class="navbar navbar-expand-sm navbar-dark">
    <a class="navbar-brand" href="#">Judul</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSmall">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSmall">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="#" class="nav-link">Story 7</a
          ></li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 8</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 9</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 10</a>
      </li>
    </ul>
  </div>
  </nav>

story8/templates/includes/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>Rafli</title>
    
  </head>
  <body>
    <!-- Navbar -->
  {% include 'includes/_navbar.html' %}
  {% block body %}
  {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
    </body>
</html>

story8/templates/index.html
{% extends 'includes/base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="box">
        <div class="accordion" name="accordion" id="acc1">Tentang Saya
            <div class="move">
                <div class="move-down" id="down">&#x2B07;</div>
                <div class="move-up" id="up">&#x2B06;</div>
            </div>
        </div>
        
        <div class="panel">
            <p>Nama saya rafli bangsawan, biasa dipanggil awan. Suka bermain gitar.
            </p>
        </div>
    </div>
    <div class="box">
        <div class="accordion">Pengalaman
            <div class="move">
                <div class="move-down">&#x2B07;</div>
                <div class="move-up">&#x2B06;</div>
            </div>
        </div>
        <div class="panel">
            <p><li>
                <ul>Panitia PERAK Fasilkom</ul>
                <ul>Panitia I-Fest Smanda</ul>
                <ul>Panitia TOBK Saimala</ul>
                </li>
            </p>
        </div>
    </div>
    <div class="box">
        <div class="accordion">Aktivitas
            <div class="move">
                <div class="move-down">&#x2B07;</div>
                <div class="move-up">&#x2B06;</div>
            </div>
        </div>
        <div class="panel">
            <p>Diam di rumah
            </p>
        </div>
    </div>
    <div class="box">
        <div class="accordion">Prestasi
            <div class="move">
                <div class="move-down" id="down1">&#x2B07;</div>
                <div class="move-up" id="up1">&#x2B06;</div>
            </div>
        </div>
        <div class="panel">
            <p><li>
                <ul>Medali Perak FLS2N 2018 Nasional</ul>
                <ul>3 Medali Emas Bali International Choir Festival 2018</ul>
                <ul>Juara 2 LCC 4 Pilar Kebangsaan MPR RI</ul>
            </li>
            </p>
        </div>
    </div>
    
</div>
<div class="buttons">
    <button class="theme">Change Theme</button>
</div>



{% endblock %}
{% block script %}
<script src="{% static 'script/accordion.js' %}"></script>
{% endblock %}

story9/templates/book.html
{% extends 'includes/base.html' %}
{% load static %}
{% block body %}
<div class="md-form mb-3 mt-0">
    <input class="form-control" id="searchBox" type="text" placeholder="Search" aria-label="Search" onchange="getData()">
    <button class="btn btn-elegant btn-rounded btn-sm my-0" id="sendButton" type="submit">Search</button>
</div>
<table class="table table-dark" id="theTable">
</table>
{% endblock %}
{% block script %}
<script src="{% static 'script/book.js' %}"></script>
{% endblock %}

story9/templates/includes/_navbar.html
{% load static %}
<!DOCTYPE html>
<nav class="navbar navbar-expand-sm navbar-dark">
    <a class="navbar-brand" href="#">Judul</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSmall">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSmall">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="#" class="nav-link">Story 7</a
          ></li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 8</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 9</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Story 10</a>
      </li>
    </ul>
  </div>
  </nav>

story9/templates/includes/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>Rafli</title>
    
  </head>
  <body>
    <!-- Navbar -->
  {% include 'includes/_navbar.html' %}
  {% block body %}
  {% endblock %}
  {% block script %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>